{
 "title": "AI in Docker - Monitoring (CPU/Mem/Latency)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API request rate (/predict)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{endpoint=\"/predict\"}[1m]))"
    }
   ]
  },
  {
   "title": "p95 API latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "api_request_latency_seconds_bucket{endpoint=\"/metrics\", instance=\"ai:8000\", job=\"ai_service\", le=\"0.005\", method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Container CPU (cores, approx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", id=~\"/docker/.*\"}[1m])) by (id))\r\n"
    }
   ]
  },
  {
   "title": "Container memory working set (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, container_memory_working_set_bytes{job=\"cadvisor\", id=~\"/docker/.*\"})\r\n"
    }
   ]
  }
 ]
}